services:
  sched:
    build: scheduler 
    environment:
      WEBAPP_URI: 'http://webapp:8000'
      SECRET_KEY: 's3cret1ve'
    depends_on:
      - webapp
    volumes:
      - ./scheduler:/var/www/scheduler
    restart: always

  # web
  webapp:
    build: .
    ports:
      - 8000:8000
    environment:
      SECRET_KEY: 's3cret1ve'
      DATABASE_URI: "sqlite:///session.db"
    volumes:
      - .:/var/www/capsule
    restart: always

